name: run tests

on: [push, pull_request]

jobs:
  python-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9] # Python 3.7 is the version in our buster image

    steps:
    -
      uses: actions/checkout@v2
    -
      name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    -
      name: Install dependencies
      run: |
        sudo apt install shellcheck
        npm install eslint eslint-plugin-vue eslint-plugin-html --save-dev
        python -m pip install --upgrade pip
        pip install wheel # wheel need to be installed before mavproxy
        pip install mavproxy
        pip install pyfakefs pytest-cov pytest-timeout pylint mypy isort black
        find . -type f -name "setup.py" | xargs --max-lines=1 --replace=% python % install --user

        MAVLINK_ROUTER_PATH="/tmp/mavlink-router"
        sudo apt install autoconf g++ git libtool make pkg-config python3-future
        mkdir ${MAVLINK_ROUTER_PATH}
        git clone --depth 1 --branch master https://github.com/mavlink-router/mavlink-router ${MAVLINK_ROUTER_PATH}
        cd ${MAVLINK_ROUTER_PATH}
        git submodule update --init --recursive --quiet
        ./autogen.sh
        ./configure --disable-systemd CFLAGS='-g -O2' --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib64 --prefix=/usr
        sudo make install
        rm -rf {MAVLINK_ROUTER_PATH}
    -
      name: Run tests
      run: |
        ./.hooks/pre-push

    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: htmlcov